# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0
    - name: Set up JDK 15
      uses: actions/setup-java@v3.5.1
      with:
        java-version: 16.0.2+7
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -V -B -q package --file pom.xml
